In [1]:
from tensorflow.keras.layers import Input, SimpleRNN, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [6]:
N = 1
T = 10
D = 3
K = 2
M = 5

X = np.random.randn(N, T, D)

In [19]:
X

array([[[ 0.71435694,  0.77259639,  0.41210417],
        [-0.66429883, -1.27062152,  1.11745455],
        [ 0.70655293,  2.03633989, -0.81812258],
        [ 1.2582139 , -0.28511962, -0.40486741],
        [-1.60065865, -0.79754743, -0.83052049],
        [-1.18039352, -0.68612746,  0.23449773],
        [-0.49693063,  0.39241183, -0.45205754],
        [ 0.25113893,  0.22280935, -0.20768734],
        [ 0.80539229, -0.92424355, -1.2096712 ],
        [ 1.44787121,  0.54495313,  0.09486646]]])

In [9]:
i = Input(shape=(T,D))
x = SimpleRNN(M)(i)
x = Dense(2)(x)

model = Model(i,x)

In [10]:
print (model.summary())

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 10, 3)]           0         
_________________________________________________________________
simple_rnn_2 (SimpleRNN)     (None, 5)                 45        
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 12        
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________
None


In [11]:
Yhat = model.predict(X)
print (Yhat)

[[-1.6733268  -0.18302342]]


In [14]:
model.layers[1].get_weights()

[array([[-0.2703346 ,  0.77155143,  0.72771007, -0.05102408,  0.62772447],
        [ 0.40728015, -0.518921  ,  0.127675  , -0.6876955 , -0.78631514],
        [ 0.3666361 , -0.63421476,  0.12552327, -0.46012616, -0.29254442]],
       dtype=float32),
 array([[-0.23654628,  0.5736913 , -0.230079  ,  0.66832554, -0.33960104],
        [ 0.40374216,  0.6046921 ,  0.4632886 , -0.38439488, -0.33006674],
        [-0.2505832 , -0.19995666,  0.8545047 ,  0.40501246,  0.05488113],
        [-0.18679543, -0.426809  , -0.02678261, -0.15171367, -0.871325  ],
        [ 0.8266521 , -0.2882312 , -0.03913595,  0.46747136, -0.11622389]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [16]:
a,b,c = model.layers[1].get_weights()
print (a.shape, b.shape, c.shape)

(3, 5) (5, 5) (5,)


In [17]:
Wx,Wh,bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()

In [18]:
h_last = np.zeros(M) # initial hidden state
x = X[0]
Yhats = []
for t in range(T):
    h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
    y = h.dot(Wo) +bo
    Yhats.append(y)
    
    h_last = h

print (Yhats[-1])

[-1.67332665 -0.18302334]
